import type { Metadata } from "next";
import "./globals.css"
import SessionWrapper from "./SessionWrapper";
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: {children: React.ReactNode;}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionWrapper>{children}</SessionWrapper>
            </body>
        </html>
    );
}
